### ISSUE TITLE
Can not login by Google

### ISSUE THREAD

**Issue by Caothuludau** [bui-quang-minh/InSync#3]
When trying to login by Google, the app return nothing.

**Comment by bui-quang-minh** [comment]
The bug was cause on Google OAuth consent, Google block the unsigned instance on app release

**Comment by bui-quang-minh** [comment]
Problem related to Google OAuth method fixed. 
![image](https://github.com/user-attachments/assets/8e134ebc-abc5-42eb-821b-3d796623544f)
- Add project signingKey, realeaseKey, change to debug key.
- Add OAuth consent information
- Change project build to base on new release
- ... and more

**Comment by bui-quang-minh** [comment]
Please confirm with your test on your account
- Device tested (with apk): 
+S23
+Xiaomi note 7

**Comment by Caothuludau** [comment]
Confirm fixed on Blackshark 3.
