### ISSUE TITLE
User Home scrren display email not right

### ISSUE THREAD

**Issue by Caothuludau** [bui-quang-minh/InSync#6]
Account Minh Bui Quang email is minhbuiquangxxx@gmail.com. But in the User Home it display vlvietnamxx@gmail.com. Why?

**Comment by bui-quang-minh** [comment]
Fixed the problem. 
![image](https://github.com/user-attachments/assets/fc81f359-e3da-43fd-acfd-4334c7c891c0)
Email is actually correct, make adjustment to display only "verified" email address,

"verification": {
                    "status": "verified",
                    "strategy": "from_oauth_google",
                    "attempts": null,
                    "expire_at": null
                },

Email should now be displaying correctly.
