### ISSUE TITLE
App Shutdown when trying to  Capture new asset

### ISSUE THREAD

**Issue by Caothuludau** [bui-quang-minh/InSync#7]
Click "Start now" on "Asset Capturing" Popup, the app shutdown immediately. (On Blackshark 3)

**Comment by bui-quang-minh** [comment]
None of the device I tested with have the same problem,.. will add try catch any way..

**Comment by bui-quang-minh** [comment]
I dont understand the problem, so i made a error catching function, app shouldn't crash from now.

**Comment by bui-quang-minh** [comment]
please download to see the interaction. Or may be if posible give me remote access to the device so i can figure out the problem

**Comment by bui-quang-minh** [comment]
please check and close

**Comment by Caothuludau** [comment]
The problem is caused because the "Display pop-up windows while running in the background" permission was not allow. But this lead to the problem that the InSync App did not request this permission.
